apiVersion: v1
kind: Service
metadata:
  name: {{ include "tty-bridge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tty-bridge.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "tty-bridge.name" . }}
